# Generated by Django 6.0.1 on 2026-02-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='expertise_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
