# Generated by Django 6.0.1 on 2026-02-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_menteeprofile_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
