# Generated by Django 6.0.1 on 2026-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_mentorprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
