# Generated by Django 5.0.14 on 2026-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_menteeprofile_avatar_url_mentorprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='admission_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='campus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='student_id_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
