# Generated by Django 5.0.14 on 2026-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_menteeprofile_admission_type_menteeprofile_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
