# Generated by Django 5.0.14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_menteeprofile_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='preferred_mentor_gender',
        ),
    ]
