# Generated by Django 6.0.1 on 2026-03-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_gender_and_preferred_mentor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='student_id_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
