# Generated by Django 6.0.1 on 2026-03-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_mentee_student_id_contact_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menteeprofile",
            name="preferred_gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("no_preference", "No Preference"),
                ],
                default="no_preference",
                max_length=20,
            ),
        ),
    ]
