# Generated by Django 6.0.1 on 2026-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_mentor_gender_mentee_preferred_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='cover_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='cover_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
