# Generated by Django 6.0.1 on 2026-03-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_menteeprofile_cover_url_mentorprofile_cover_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, related_name='mentee_profiles', to='profiles.interesttag'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, related_name='mentor_profiles', to='profiles.interesttag'),
        ),
    ]
