# Generated by Django 5.2.12 on 2026-04-09 15:59

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_interesttag_menteeprofile_bio_mentorprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='verification_document',
            field=models.FileField(blank=True, upload_to=profiles.models.verification_document_upload_path),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='verification_document',
            field=models.FileField(blank=True, upload_to=profiles.models.verification_document_upload_path),
        ),
    ]
