# Generated by Django 5.2.17 on 2026-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_completion_and_mentor_student_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verificationdocument',
            name='verification_doc_one_profile',
        ),
        migrations.AddConstraint(
            model_name='verificationdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mentee__isnull', True), ('mentor__isnull', False)), models.Q(('mentee__isnull', False), ('mentor__isnull', True)), _connector='OR'), name='verification_doc_one_profile'),
        ),
    ]
