# Generated by Django 5.2.17 on 2026-09-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_verificationdocument_verification_doc_one_profile_and_more'),
        ('profiles', '0018_repair_menteeprofile_difficulty_level'),
    ]

    operations = [
    ]
