# Generated by Django 5.2.17 on 2026-09-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_merge_20260918_1908'),
        ('profiles', '0019_remove_verificationdocument_verification_doc_one_profile_and_more'),
    ]

    operations = [
    ]
