# Generated by Django 5.2.12 on 2026-09-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_merge_20260918_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='admission_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='campus',
            field=models.CharField(blank=True, default='Main', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
