# Generated by Django 5.2.12 on 2026-09-20 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0022_replace_bsit_curriculum'),
        ('profiles', '0021_mentorprofile_admission_type_mentorprofile_campus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menteeprofile',
            index=models.Index(fields=['sex', 'approved'], name='prof_mentee_sex_appr'),
        ),
        migrations.AddIndex(
            model_name='menteeprofile',
            index=models.Index(fields=['approved'], name='prof_mentee_approved'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['gender', 'approved'], name='prof_mentor_gender_appr'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['approved'], name='prof_mentor_approved'),
        ),
    ]
