services:
  - type: web
    name: peerlink
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn capstone_site.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: DJANGO_DEBUG
        value: "False"
      - key: TRUST_X_FORWARDED_PROTO
        value: "true"
      - key: DJANGO_ADMIN_URL
        value: manage
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_SSLMODE
        value: require
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: ALLOWED_EMAIL_DOMAINS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
