"""
Django settings for capstone_site project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file at project root
load_dotenv(BASE_DIR / '.env')


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


def _env_csv(name: str) -> list[str]:
    raw = os.environ.get(name, "")
    return [part.strip() for part in raw.split(",") if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In development, you can store this in the .env file as DJANGO_SECRET_KEY
DEBUG = _env_bool("DJANGO_DEBUG", default=False)

_secret_key_env = (os.environ.get('DJANGO_SECRET_KEY') or '').strip()
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    # Dev-only fallback to avoid startup failure when setting up locally.
    SECRET_KEY = 'django-insecure-dev-only-change-me'
else:
    SECRET_KEY = ''

if not DEBUG:
    if not SECRET_KEY:
        raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is False.')
    if SECRET_KEY.startswith('django-insecure') or 'change-me' in SECRET_KEY.lower():
        raise RuntimeError('DJANGO_SECRET_KEY appears weak or placeholder-like in production.')

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = _env_csv("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _env_csv("DJANGO_CSRF_TRUSTED_ORIGINS")

if not DEBUG:
    if not ALLOWED_HOSTS:
        raise RuntimeError('DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG is False.')
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_SSL_REDIRECT = True
    if _env_bool('TRUST_X_FORWARDED_PROTO', default=True):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'axes',  # Login attempt rate limiting
    'rest_framework',
    'accounts',
    'profiles',
    'matching',
    'api',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Must be after AuthenticationMiddleware
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'capstone_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'matching.context_processors.notification_counts',
                'matching.context_processors.sidebar_user',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

force_sqlite = os.environ.get("FORCE_SQLITE", "").lower() == "true"
db_name = os.environ.get("DB_NAME")
if db_name and not force_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': os.environ.get("DB_USER", ""),
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': os.environ.get("DB_HOST", "localhost"),
            'PORT': os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production: collectstatic output
# Dashboard and landing assets: /static/ serves from these dirs (e.g. /static/assets/app.jsx, /static/output.css).
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dashboard',
    BASE_DIR / 'frontend' / 'landing',
]

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default file storage: Cloudinary (if set) else Google Drive else filesystem
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
if os.environ.get("CLOUDINARY_CLOUD_NAME"):
    STORAGES["default"] = {"BACKEND": "api.cloudinary_storage.CloudinaryStorage"}
elif os.environ.get("DRIVE_SERVICE_ACCOUNT_JSON"):
    STORAGES["default"] = {"BACKEND": "api.drive_storage.GoogleDriveStorage"}
else:
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": MEDIA_ROOT, "base_url": MEDIA_URL},
    }

# WhiteNoise for serving static files in production (legacy setting, STORAGES used above)
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django authentication
LOGIN_REDIRECT_URL = '/app/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
# Password reset link expires after 10 minutes (seconds)
PASSWORD_RESET_TIMEOUT = 600

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Must be first
    'accounts.auth_backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# django-allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
SOCIALACCOUNT_LOGIN_ON_GET = True
# Allow linking Google accounts to existing email/password accounts
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/drive.file",  # Create/access app-created Drive files
        ],
        "AUTH_PARAMS": {"prompt": "select_account", "access_type": "offline"},
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
    }
}

SOCIALACCOUNT_ADAPTER = "accounts.adapters.RoleAwareSocialAccountAdapter"

# REST framework: Django session auth for API (use IsAuthenticated on views that need it)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Email (Gmail SMTP with app password)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'   
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Set these environment variables on your system:
#   EMAIL_HOST_USER      -> your full Gmail address
#   EMAIL_HOST_PASSWORD  -> your 16‑character app password (NOT your login password)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Logging: lower verbosity in production so expensive views (like matching) aren't slowed by logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        # Keep Django's own logs at a reasonable level
        "django": {
            "handlers": ["console"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
        # App-specific modules can log info in dev, but default to warning in prod
        "matching": {
          "handlers": ["console"],
          "level": "INFO" if DEBUG else "WARNING",
          "propagate": False,
        },
        "api": {
          "handlers": ["console"],
          "level": "INFO" if DEBUG else "WARNING",
          "propagate": False,
        },
    },
}

# django-axes: Login attempt rate limiting
# Track failed login attempts and temporarily lock accounts after threshold exceeded
from datetime import timedelta

AXES_FAILURE_LIMIT = 5  # Lock account after 5 failed attempts
AXES_COOLOFF_TIME = timedelta(minutes=15)  # Lockout duration: 15 minutes
AXES_LOCKOUT_TEMPLATE = None  # Use DRF response for API lockouts
AXES_VERBOSE = True  # Log detailed information about attempts
AXES_RESET_ON_SUCCESS = True  # Reset counter on successful login
