"""
Django settings for capstone_site project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file at project root
load_dotenv(BASE_DIR / '.env')


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


def _env_csv(name: str) -> list[str]:
    raw = os.environ.get(name, "")
    return [part.strip() for part in raw.split(",") if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In development, you can store this in the .env file as DJANGO_SECRET_KEY
DEBUG = _env_bool("DJANGO_DEBUG", default=False)

_secret_key_env = (os.environ.get('DJANGO_SECRET_KEY') or '').strip()
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    # Dev-only fallback to avoid startup failure when setting up locally.
    SECRET_KEY = 'django-insecure-dev-only-change-me'
else:
    SECRET_KEY = ''

if not DEBUG:
    if not SECRET_KEY:
        raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is False.')
    if SECRET_KEY.startswith('django-insecure') or 'change-me' in SECRET_KEY.lower():
        raise RuntimeError('DJANGO_SECRET_KEY appears weak or placeholder-like in production.')

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = _env_csv("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _env_csv("DJANGO_CSRF_TRUSTED_ORIGINS")
CSRF_FAILURE_VIEW = 'capstone_site.security.csrf_failure'
_render_host = (os.environ.get("RENDER_EXTERNAL_HOSTNAME") or "").strip()
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)
if _render_host:
    _render_origin = f"https://{_render_host}"
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)

if not DEBUG:
    if not ALLOWED_HOSTS:
        if os.environ.get("RENDER"):
            ALLOWED_HOSTS = [".onrender.com"]
        else:
            raise RuntimeError('DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG is False.')
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_SSL_REDIRECT = True
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
    if _env_bool('TRUST_X_FORWARDED_PROTO', default=True):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'axes',  # Login attempt rate limiting
    'rest_framework',
    'accounts.apps.AccountsConfig',
    'profiles',
    'matching',
    'api',
    'dbbackup',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'capstone_site.security.SecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.jwt_middleware.JWTAuthenticationMiddleware',
    'capstone_site.security.ApiAuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Must be after AuthenticationMiddleware
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'capstone_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'matching.context_processors.notification_counts',
                'matching.context_processors.sidebar_user',
                'capstone_site.security.csp_nonce_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

force_sqlite = os.environ.get("FORCE_SQLITE", "").lower() == "true"
db_name = os.environ.get("DB_NAME")
if db_name and not force_sqlite:
    db_host = os.environ.get("DB_HOST", "localhost")
    db_port = os.environ.get("DB_PORT")
    if not db_port:
        db_port = "6543" if "pooler.supabase.com" in db_host.lower() else "5432"
    elif "pooler.supabase.com" in db_host.lower() and db_port == "5432":
        db_port = "6543"

    db_options = {}
    if "supabase" in db_host.lower() or os.environ.get("DB_SSLMODE"):
        db_options["sslmode"] = os.environ.get("DB_SSLMODE", "require")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': os.environ.get("DB_USER", ""),
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': db_host,
            'PORT': db_port,
            'OPTIONS': db_options,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production: collectstatic output
# Dashboard and landing assets: /static/ serves from these dirs (e.g. /static/assets/app.jsx, /static/output.css).
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dashboard',
    BASE_DIR / 'frontend' / 'landing',
]

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Feature flags: explicitly disable Google integrations unless enabled.
ENABLE_GOOGLE_CALENDAR = _env_bool("ENABLE_GOOGLE_CALENDAR", default=False)
ENABLE_GOOGLE_DRIVE_API = _env_bool("ENABLE_GOOGLE_DRIVE_API", default=False)

# Cloudinary media storage configuration
CLOUDINARY_CLOUD_NAME = os.environ.get("CLOUDINARY_CLOUD_NAME", "").strip()
CLOUDINARY_API_KEY = os.environ.get("CLOUDINARY_API_KEY", "").strip()
CLOUDINARY_API_SECRET = os.environ.get("CLOUDINARY_API_SECRET", "").strip()
if CLOUDINARY_CLOUD_NAME:
    import cloudinary
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True,
    )

STORAGES = {
    "staticfiles": {
        "BACKEND": "capstone_site.storage.WhiteNoiseStaticFilesStorage",
    },
}
if CLOUDINARY_CLOUD_NAME:
    STORAGES["default"] = {"BACKEND": "api.cloudinary_storage.CloudinaryStorage"}
else:
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": MEDIA_ROOT, "base_url": MEDIA_URL},
    }

# WhiteNoise for serving static files in production (legacy setting, STORAGES used above)
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django authentication
LOGIN_REDIRECT_URL = '/app/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
# Password reset link expires after 10 minutes (seconds)
PASSWORD_RESET_TIMEOUT = 600

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Must be first
    'accounts.auth_backends.EmailOrUsernameModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# django-allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_AUTO_SIGNUP = True
# Allow linking Google accounts to existing email/password accounts
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {"prompt": "select_account", "access_type": "offline"},
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
    }
}

SOCIALACCOUNT_ADAPTER = "accounts.adapters.RoleAwareSocialAccountAdapter"

# REST framework: Django session auth for API (public views must opt out explicitly)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Upload ceilings (verification docs are capped at 5 MB in forms)
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200

# Email (Gmail SMTP with app password)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))

# Set these environment variables on your system:
#   EMAIL_HOST_USER      -> your full Gmail address
#   EMAIL_HOST_PASSWORD  -> your 16‑character app password (NOT your login password)
EMAIL_HOST_USER = (os.environ.get('EMAIL_HOST_USER') or '').strip()
EMAIL_HOST_PASSWORD = (os.environ.get('EMAIL_HOST_PASSWORD') or '').strip()

_from_email = (os.environ.get('DEFAULT_FROM_EMAIL') or '').strip()
if EMAIL_HOST_USER and (not _from_email or EMAIL_HOST_USER.lower() not in _from_email.lower()):
    DEFAULT_FROM_EMAIL = f'PeerLink <{EMAIL_HOST_USER}>'
else:
    DEFAULT_FROM_EMAIL = _from_email or EMAIL_HOST_USER

# Institutional email domains restriction (optional, comma-separated)
# Set in .env as ALLOWED_EMAIL_DOMAINS=@domain1.edu,@domain2.edu
# Leave empty to allow any email
ALLOWED_EMAIL_DOMAINS = _env_csv('ALLOWED_EMAIL_DOMAINS')

# Logging: lower verbosity in production so expensive views (like matching) aren't slowed by logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        # Keep Django's own logs at a reasonable level
        "django": {
            "handlers": ["console"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
        # App-specific modules can log info in dev, but default to warning in prod
        "matching": {
          "handlers": ["console"],
          "level": "INFO" if DEBUG else "WARNING",
          "propagate": False,
        },
        "api": {
          "handlers": ["console"],
          "level": "INFO" if DEBUG else "WARNING",
          "propagate": False,
        },
    },
}

# django-axes: Login attempt rate limiting
# Track failed login attempts and temporarily lock accounts after threshold exceeded
from datetime import timedelta

AXES_FAILURE_LIMIT = 5  # Lock account after 5 failed attempts
AXES_COOLOFF_TIME = timedelta(minutes=15)  # Lockout duration: 15 minutes
AXES_LOCKOUT_TEMPLATE = None  # Use DRF response for API lockouts
AXES_LOCKOUT_CALLABLE = "accounts.lockout_utils.axes_lockout_response"
AXES_VERBOSE = True  # Log detailed information about attempts
AXES_RESET_ON_SUCCESS = True  # Reset counter on successful login
AXES_LOCKOUT_BY_COMBINATION_USER_AND_IP = True
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
_behind_proxy = _env_bool("TRUST_X_FORWARDED_PROTO", default=not DEBUG)
if _behind_proxy:
    AXES_IPWARE_PROXY_COUNT = 1
    AXES_IPWARE_META_PRECEDENCE_ORDER = ("HTTP_X_FORWARDED_FOR", "REMOTE_ADDR")
else:
    AXES_IPWARE_PROXY_COUNT = 0
    AXES_IPWARE_META_PRECEDENCE_ORDER = ("REMOTE_ADDR",)

# Authentication/session performance tuning
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", str(60 * 60 * 24 * 7)))

REDIS_URL = os.environ.get("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 300,
            "KEY_PREFIX": "matching",
        }
    }
    # Cache-backed session reads are much faster than DB-only sessions.
    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
    SESSION_CACHE_ALIAS = "default"
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "matching-local-cache",
            "TIMEOUT": 300,
        }
    }

JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY", SECRET_KEY)
JWT_ACCESS_TTL_SECONDS = int(os.environ.get("JWT_ACCESS_TTL_SECONDS", "1800"))
JWT_REFRESH_TTL_SECONDS = int(os.environ.get("JWT_REFRESH_TTL_SECONDS", str(60 * 60 * 24 * 14)))
JWT_ROTATE_REFRESH_TOKENS = _env_bool("JWT_ROTATE_REFRESH_TOKENS", default=True)
JWT_REFRESH_COOKIE_NAME = os.environ.get("JWT_REFRESH_COOKIE_NAME", "pl_refresh")
JWT_REFRESH_COOKIE_PATH = "/api/auth/"

_admin_url = (os.environ.get("DJANGO_ADMIN_URL") or "").strip().strip("/")
if _admin_url:
    ADMIN_URL = f"{_admin_url}/"
elif DEBUG:
    ADMIN_URL = "admin/"
else:
    ADMIN_URL = "manage/"

# django-dbbackup
BACKUP_DIR = Path(os.environ.get("BACKUP_DIR", BASE_DIR / "backups"))
try:
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    BACKUP_DIR = Path("/tmp/backups")
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)

# django-dbbackup v5 reads storage configuration from STORAGES["dbbackup"].
STORAGES["dbbackup"] = {
    "BACKEND": "django.core.files.storage.FileSystemStorage",
    "OPTIONS": {
        "location": str(BACKUP_DIR),
    },
}
DBBACKUP_CLEANUP_KEEP = int(os.environ.get("DBBACKUP_CLEANUP_KEEP", "20"))
