import SubjectSkillPreferences, {
  MAX_SUBJECTS,
  MAX_TOPICS_PER_SUBJECT,
  MAX_COMPETENCIES_PER_SUBJECT,
  MAX_COMPETENCIES_PER_TOPIC,
  MAX_COMPETENCIES_TOTAL,
  ROLE_PREFERENCE_LIMITS,
  ROLE_LIMITS,
  getRolePreferenceLimits,
  getRoleLimits,
  CANONICAL_CURRICULUM,
  NEU_STYLES,
} from "./SubjectSkillPreferences.jsx";

export {
  MAX_SUBJECTS,
  MAX_TOPICS_PER_SUBJECT,
  MAX_COMPETENCIES_PER_SUBJECT,
  MAX_COMPETENCIES_PER_TOPIC,
  MAX_COMPETENCIES_TOTAL,
  ROLE_PREFERENCE_LIMITS,
  ROLE_LIMITS,
  getRolePreferenceLimits,
  getRoleLimits,
  CANONICAL_CURRICULUM,
  NEU_STYLES,
};

export default SubjectSkillPreferences;
