# Generated by Django 5.2.12 on 2026-09-13 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersecuritystate_is_onboarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MENTEE', 'Mentee'), ('STUDENT_MENTOR', 'Student Mentor'), ('INSTRUCTOR_MENTOR', 'Instructor Mentor'), ('COORDINATOR', 'Coordinator')], max_length=20)),
                ('approval_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=20)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('campus', models.CharField(blank=True, default='', max_length=100)),
                ('program', models.CharField(blank=True, default='BSIT', max_length=100)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LETTER_OF_INTENT', 'Letter of Intent'), ('STUDY_LOAD', 'Study Load'), ('GRADES', 'Grades'), ('FACULTY_VERIFICATION', 'Faculty Verification')], max_length=50)),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'document_type'], name='acc_doc_user_type')],
            },
        ),
    ]
