# Generated by Django 5.2.17 on 2026-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_mentordocument'),
        ('profiles', '0019_remove_verificationdocument_verification_doc_one_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='profiles.interesttag'),
        ),
    ]
