# Generated by Django 5.2.12 on 2026-09-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_avatar_url_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admission_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Approval'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, default='Main', max_length=100),
        ),
    ]
