# Generated by Django 5.2.12 on 2026-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_admission_type_userprofile_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active / Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
