# Generated by Django 5.2.12 on 2026-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active / Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
