# Generated by Django 5.2.17 on 2026-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_userprofile_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordocument',
            name='document_type',
            field=models.CharField(choices=[('LETTER_OF_INTENT', 'Letter of Intent'), ('STUDY_LOAD', 'Study Load'), ('GRADES', 'Grades'), ('FACULTY_VERIFICATION', 'Faculty Verification'), ('PROOF_OF_ENROLLMENT', 'Proof of Enrollment'), ('STUDENT_ID', 'Student / Employee ID Card'), ('CERTIFICATE', 'Certificate'), ('APPLICATION', 'Application Form')], max_length=50),
        ),
    ]
