"""
API views package: request handlers and shared helpers.

- helpers: shared utilities used by views and controllers
- notifications, subjects, topics, mentees: feature-specific view handlers
"""

from .helpers import (
    logger,
    _avatar_url,
    _serialize_mentor_for_matching,
    _serialize_mentee_for_matching,
    _json_body,
    _get_payload,
    _get_int,
    _get_str,
    _get_role_flags,
    _resolve_account_role,
    _validate_role,
    _rate_limit,
    audit_log,
    _require_mentor,
    _require_mentee,
    _require_role,
    _require_staff,
    get_mentor_approved,
    get_mentee_approved,
    APPROVAL_LIST_CACHE_TTL,
    get_approval_list_cache_key,
    invalidate_approval_cache_mentor,
    invalidate_approval_cache_mentee,
    _serialize_notification,
    _serialize_subject,
    _serialize_topic,
    _serialize_mentee,
    get_subjects_list,
    invalidate_subjects_cache,
    _parse_datetime,
)
from .notifications import (
    notifications_list,
    notifications_mark_all_read,
    notification_mark_read,
    notifications_unread_count,
)
from .subjects import (
    subjects_list,
    subject_create,
    subject_update,
    subject_delete,
)
from .topics import (
    topics_list,
    topic_create,
    topic_update,
    topic_archive_toggle,
    topic_delete,
)
from .mentees import mentees_list

__all__ = [
    "logger",
    "_avatar_url",
    "_serialize_mentor_for_matching",
    "_serialize_mentee_for_matching",
    "_json_body",
    "_get_payload",
    "_get_int",
    "_get_str",
    "_get_role_flags",
    "_resolve_account_role",
    "_validate_role",
    "_rate_limit",
    "_require_mentor",
    "_require_mentee",
    "_require_role",
    "_require_staff",
    "get_mentor_approved",
    "get_mentee_approved",
    "APPROVAL_LIST_CACHE_TTL",
    "get_approval_list_cache_key",
    "invalidate_approval_cache_mentor",
    "invalidate_approval_cache_mentee",
    "_serialize_notification",
    "_serialize_subject",
    "_serialize_topic",
    "_serialize_mentee",
    "get_subjects_list",
    "invalidate_subjects_cache",
    "_parse_datetime",
    "notifications_list",
    "notifications_mark_all_read",
    "notification_mark_read",
    "notifications_unread_count",
    "subjects_list",
    "subject_create",
    "subject_update",
    "subject_delete",
    "topics_list",
    "topic_create",
    "topic_update",
    "topic_archive_toggle",
    "topic_delete",
    "mentees_list",
]
