# Generated by Django 6.0.1 on 2026-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsession',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
