# Generated by Django 6.0.1 on 2026-02-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_topics_and_session_topic'),
        ('profiles', '0003_mentorprofile_approved'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mentoringsession',
            index=models.Index(fields=['mentor', 'scheduled_at'], name='matching_me_mentor__24cf65_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringsession',
            index=models.Index(fields=['mentee', 'scheduled_at'], name='matching_me_mentee__ad7cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringsession',
            index=models.Index(fields=['status', 'scheduled_at'], name='matching_me_status_8f9bff_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentoringsession',
            constraint=models.CheckConstraint(condition=models.Q(duration_minutes__gte=15), name='session_duration_minutes_gte_15'),
        ),
    ]
