# Generated by Django 5.0.14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_gender_and_preferred_mentor_gender'),
        ('matching', '0005_mentoringsession_matching_me_mentor__24cf65_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeMentorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.mentorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('mentee', 'mentor')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_tab',
            field=models.CharField(blank=True, help_text='Tab to open when notification is clicked (e.g. matching, sessions).', max_length=50),
        ),
    ]
