# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_menteementorrequest_notification_action_tab'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='matching_notif_user_read'),
        ),
        migrations.AddIndex(
            model_name='menteementorrequest',
            index=models.Index(fields=['mentor', '-created_at'], name='matching_mmr_mentor_created'),
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_tab',
            field=models.CharField(blank=True, default='', help_text='Tab to open when notification is clicked (e.g. matching, sessions).', max_length=50),
        ),
    ]
