# Generated by Django 6.0.1 on 2026-03-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_announcement_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsession',
            name='meeting_notes',
            field=models.TextField(blank=True, help_text='Notes taken during or after the session.'),
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Agenda or materials when scheduling.'),
        ),
    ]
