# Generated by Django 6.0.1 on 2026-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_add_meeting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete; when set, hidden from lists.', null=True),
        ),
    ]
