# Generated by Django 6.0.1 on 2026-03-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_audit_log'),
        ('profiles', '0008_mentee_student_id_contact_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteementorrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menteementorrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='menteementorrequest',
            index=models.Index(fields=['mentor', 'accepted'], name='matching_mmr_mentor_accepted'),
        ),
    ]
