# Generated by Django 5.2.12 on 2026-05-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0016_remove_mentoring_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_tab',
            field=models.CharField(blank=True, default='', help_text='Tab to open when notification is clicked (e.g. matching).', max_length=50),
        ),
    ]
