# Generated by Django 5.2.12 on 2026-06-06 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0018_subject_category_minor_subjects'),
        ('profiles', '0012_menteeprofile_verification_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject__name', 'name']},
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MatchingDatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('real', 'Real'), ('synthetic', 'Synthetic')], default='real', max_length=16)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_records', to='profiles.menteeprofile')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_records', to='profiles.mentorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingDatasetTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor')], max_length=10)),
                ('topic_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='matching.matchingdatasetrecord')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_topic_links', to='matching.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_links', to='matching.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('active', 'Active'), ('retired', 'Retired')], default='staged', max_length=16)),
                ('artifact_path', models.CharField(blank=True, default='', max_length=255)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('training_rows', models.PositiveIntegerField(default=0)),
                ('topic_count_active_at_train', models.PositiveIntegerField(default=0)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_metadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTopicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10)),
                ('is_active_selection', models.BooleanField(default=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_preferences', to='matching.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_preferences', to='matching.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='matchingdatasetrecord',
            index=models.Index(fields=['source', '-created_at'], name='mt_ds_source_created'),
        ),
        migrations.AddIndex(
            model_name='matchingdatasettopic',
            index=models.Index(fields=['dataset_record', 'role'], name='mt_dst_record_role'),
        ),
        migrations.AddIndex(
            model_name='matchingdatasettopic',
            index=models.Index(fields=['topic'], name='mt_dst_topic'),
        ),
        migrations.AddIndex(
            model_name='modelmetadata',
            index=models.Index(fields=['status', '-created_at'], name='mt_model_status_created'),
        ),
        migrations.AddIndex(
            model_name='usertopicpreference',
            index=models.Index(fields=['user', 'target', 'is_active_selection'], name='mt_utp_user_target_act'),
        ),
        migrations.AddIndex(
            model_name='usertopicpreference',
            index=models.Index(fields=['topic'], name='mt_utp_topic'),
        ),
    ]
