from django.urls import path

from .controllers.account_controller import (
    health,
    csrf,
    auth_login,
    auth_logout,
    auth_register,
    me,
    update_account,
    upload_avatar,
    upload_cover,
    update_bio,
    update_tags,
    tag_suggestions,
    update_mentee_profile,
    update_mentee_matching_profile,
    update_mentor_profile,
)
from .controllers.matching_controller import (
    run_matching,
    mentee_recommendations,
    mentee_choose_mentor,
    mentor_requests,
    mentor_accept_mentee,
    my_mentor,
    mentor_profile_by_user_id,
)
from .controllers.sessions_controller import (
    sessions_list,
    session_create,
    session_reschedule,
    session_update_status,
    session_update_meeting_notes,
)
from .controllers.approvals_controller import (
    pending_list,
    approve_mentor,
    reject_mentor,
    approve_mentee,
    reject_mentee,
)
from .controllers.announcements_controller import (
    announcements_list,
    announcement_create,
    announcement_soft_delete,
    comments_list,
    comment_create,
)
from .controllers.backup_controller import (
    backup_list,
    backup_create,
    backup_download,
    backup_restore,
    backup_restore_by_id,
    backup_delete,
)
from .controllers.drive_controller import (
    drive_upload,
    drive_list,
    drive_connected,
)
from .controllers.activity_controller import activity_logs_list
from .controllers.search_controller import search, user_public_profile
from .controllers.posts_controller import (
    posts_list,
    posts_feed,
    post_detail,
    post_create,
    post_like,
    post_delete,
    post_comments_list,
    post_comment_create,
    gallery,
    profile_stats,
)
from .views import (
    notifications_list,
    notifications_mark_all_read,
    notification_mark_read,
    notifications_unread_count,
    subjects_list,
    subject_create,
    subject_update,
    subject_delete,
    topics_list,
    mentees_list,
)

urlpatterns = [
    path('health/', health, name='api-health'),
    path('csrf/', csrf, name='api-csrf'),
    path('matching/run/', run_matching, name='api-matching-run'),
    path('matching/mentee-recommendations/', mentee_recommendations, name='api-matching-mentee-recommendations'),
    path('matching/mentee-choose-mentor/', mentee_choose_mentor, name='api-matching-mentee-choose-mentor'),
    path('matching/mentor-requests/', mentor_requests, name='api-matching-mentor-requests'),
    path('matching/mentor-accept-mentee/', mentor_accept_mentee, name='api-matching-mentor-accept-mentee'),
    path('matching/my-mentor/', my_mentor, name='api-matching-my-mentor'),
    path('matching/mentor-profile/<int:user_id>/', mentor_profile_by_user_id, name='api-matching-mentor-profile-by-user-id'),
    path('auth/login/', auth_login, name='api-auth-login'),
    path('auth/logout/', auth_logout, name='api-auth-logout'),
    path('auth/register/', auth_register, name='api-auth-register'),
    path('me/', me, name='api-me'),
    path('me/update/', update_account, name='api-me-update'),
    path('me/avatar/', upload_avatar, name='api-me-avatar'),
    path('me/cover/', upload_cover, name='api-me-cover'),
    path('me/mentee-profile/', update_mentee_profile, name='api-me-mentee-profile'),
    path('me/mentee-matching/', update_mentee_matching_profile, name='api-me-mentee-matching'),
    path('me/mentor-profile/', update_mentor_profile, name='api-me-mentor-profile'),
    path('me/bio/', update_bio, name='api-me-bio'),
    path('me/tags/', update_tags, name='api-me-tags'),
    path('tags/suggestions/', tag_suggestions, name='api-tags-suggestions'),
    path('sessions/', sessions_list, name='api-sessions-list'),
    path('sessions/create/', session_create, name='api-sessions-create'),
    path('sessions/<int:session_id>/reschedule/', session_reschedule, name='api-sessions-reschedule'),
    path('sessions/<int:session_id>/status/', session_update_status, name='api-sessions-status'),
    path('sessions/<int:session_id>/meeting-notes/', session_update_meeting_notes, name='api-sessions-meeting-notes'),
    path('approvals/pending/', pending_list, name='api-approvals-pending'),
    path('approvals/approve-mentor/', approve_mentor, name='api-approvals-approve-mentor'),
    path('approvals/reject-mentor/', reject_mentor, name='api-approvals-reject-mentor'),
    path('approvals/approve-mentee/', approve_mentee, name='api-approvals-approve-mentee'),
    path('approvals/reject-mentee/', reject_mentee, name='api-approvals-reject-mentee'),
    path('notifications/', notifications_list, name='api-notifications-list'),
    path('notifications/unread-count/', notifications_unread_count, name='api-notifications-unread-count'),
    path('notifications/mark-all-read/', notifications_mark_all_read, name='api-notifications-mark-all-read'),
    path('notifications/<int:notification_id>/read/', notification_mark_read, name='api-notifications-read'),
    path('subjects/', subjects_list, name='api-subjects-list'),
    path('subjects/create/', subject_create, name='api-subjects-create'),
    path('subjects/<int:subject_id>/update/', subject_update, name='api-subjects-update'),
    path('subjects/<int:subject_id>/delete/', subject_delete, name='api-subjects-delete'),
    path('topics/', topics_list, name='api-topics-list'),
    path('mentees/', mentees_list, name='api-mentees-list'),
    path('announcements/', announcements_list, name='api-announcements-list'),
    path('announcements/create/', announcement_create, name='api-announcements-create'),
    path('announcements/<int:announcement_id>/delete/', announcement_soft_delete, name='api-announcements-delete'),
    path('comments/<str:target_type>/<int:target_id>/', comments_list, name='api-comments-list'),
    path('comments/create/', comment_create, name='api-comments-create'),
    path('backup/', backup_list, name='api-backup-list'),
    path('backup/create/', backup_create, name='api-backup-create'),
    path('backup/restore/', backup_restore, name='api-backup-restore'),
    path('backup/<str:backup_id>/download/', backup_download, name='api-backup-download'),
    path('backup/<str:backup_id>/restore/', backup_restore_by_id, name='api-backup-restore-by-id'),
    path('backup/<str:backup_id>/delete/', backup_delete, name='api-backup-delete'),
    path('drive/connected/', drive_connected, name='api-drive-connected'),
    path('drive/upload/', drive_upload, name='api-drive-upload'),
    path('drive/files/', drive_list, name='api-drive-list'),
    path('activity-logs/', activity_logs_list, name='api-activity-logs'),
    path('search/', search, name='api-search'),
    path('users/<int:user_id>/profile/', user_public_profile, name='api-user-public-profile'),
    path('posts/', posts_list, name='api-posts-list'),
    path('posts/feed/', posts_feed, name='api-posts-feed'),
    path('posts/create/', post_create, name='api-posts-create'),
    path('posts/<int:post_id>/', post_detail, name='api-posts-detail'),
    path('posts/<int:post_id>/like/', post_like, name='api-posts-like'),
    path('posts/<int:post_id>/delete/', post_delete, name='api-posts-delete'),
    path('posts/<int:post_id>/comments/', post_comments_list, name='api-posts-comments-list'),
    path('posts/<int:post_id>/comments/create/', post_comment_create, name='api-posts-comments-create'),
    path('gallery/', gallery, name='api-gallery'),
    path('profile-stats/', profile_stats, name='api-profile-stats'),
]
